# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('imageFile', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to=images.models.PathAndRename('media'), width_field='width_field')),
                ('thumbnailImg', models.ImageField(blank=True, default=None, height_field='height_field', null=True, upload_to=images.models.PathAndRename('media'), width_field='width_field')),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
