# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.TextField(default='')),
                ('name', models.BooleanField(default=False)),
                ('password', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
